import './container_widget.dart';
import 'package:flutter/material.dart';
import 'package:flutter_gradient_colors/flutter_gradient_colors.dart';

// ignore: must_be_immutable
class NewColors extends StatelessWidget {
  List colorNames = [
    {"name": "WarmFlame", "color": GradientColors.warmFlame},
    {"name": "NightFade", "color": GradientColors.nightFade},
    {"name": "SpringWarmt", "color": GradientColors.springWarmt},
    {"name": "JuicyPeach", "color": GradientColors.juicyPeach},
    {"name": "LadyLips", "color": GradientColors.ladyLips},
    {"name": "SunnyMorning", "color": GradientColors.sunnyMorning},
    {"name": "RainyAshville", "color": GradientColors.rainyAshville},
    {"name": "FrozenDreams", "color": GradientColors.frozenDreams},
    {"name": "WinterNeva", "color": GradientColors.winterNeva},
    {"name": "DustyGrass", "color": GradientColors.dustyGrass},
    {"name": "TemptingAzure", "color": GradientColors.temptingAzure},
    {"name": "HeavyRain", "color": GradientColors.heavyRain},
    {"name": "AmyCrisp", "color": GradientColors.amyCrisp},
    {"name": "MeanFruit", "color": GradientColors.meanFruit},
    {"name": "LightBluee", "color": GradientColors.lightBluee},
    {"name": "RipeMalinka", "color": GradientColors.ripeMalinka},
    {"name": "CloudyKnoxville", "color": GradientColors.cloudyKnoxville},
    {"name": "MalibuBeach", "color": GradientColors.malibuBeach},
    {"name": "NewLife", "color": GradientColors.newLife},
    {"name": "TrueSunset", "color": GradientColors.trueSunset},
    {"name": "MorpheusDen", "color": GradientColors.morpheusDen},
    {"name": "RareWind", "color": GradientColors.rareWind},
    {"name": "WildApple", "color": GradientColors.wildApple},
    {"name": "PlumPlate", "color": GradientColors.plumPlate},
    {"name": "EverlastingSky", "color": GradientColors.everlastingSky},
    {"name": "HappyFisher", "color": GradientColors.happyFisher},
    {"name": "BlessingGet", "color": GradientColors.blessingGet},
    {"name": "SharpeyeEagle", "color": GradientColors.sharpeyeEagle},
    {"name": "LiadogaBottom", "color": GradientColors.liadogaBottom},
    {"name": "LemonGate", "color": GradientColors.lemonGate},
    {"name": "ItmeoBranding", "color": GradientColors.itmeoBranding},
    {"name": "ZeusMiracle", "color": GradientColors.zeusMiracle},
    {"name": "DeepBlue", "color": GradientColors.deepBlue},
    {"name": "HappyAcid", "color": GradientColors.happyAcid},
    {"name": "AwesomePine", "color": GradientColors.awesomePine},
    {"name": "NewYork", "color": GradientColors.newYork},
    {"name": "MixedHopes", "color": GradientColors.mixedHopes},
    {"name": "FlyHigh", "color": GradientColors.flyHigh},
    {"name": "FreshMilk", "color": GradientColors.freshMilk},
    {"name": "SnowAgain", "color": GradientColors.snowAgain},
    {"name": "FebruaryInk", "color": GradientColors.februaryInk},
    {"name": "KindSteel", "color": GradientColors.kindSteel},
    {"name": "SoftGrass", "color": GradientColors.softGrass},
    {"name": "GrownEarly", "color": GradientColors.grownEarly},
    {"name": "SharpBlues", "color": GradientColors.sharpBlues},
    {"name": "ShadyWater", "color": GradientColors.shadyWater},
    {"name": "DirtyBeauty", "color": GradientColors.dirtyBeauty},
    {"name": "GreatWhale", "color": GradientColors.greatWhale},
    {"name": "TeenNotebook", "color": GradientColors.teenNotebook},
    {"name": "PoliteRumors", "color": GradientColors.politeRumors},
    {"name": "RedSalvation", "color": GradientColors.redSalvation},
    {"name": "NightParty", "color": GradientColors.nightParty},
    {"name": "SkyGlider", "color": GradientColors.skyGlider},
    {"name": "HeavenPeach", "color": GradientColors.heavenPeach},
    {"name": "PurpleDivision", "color": GradientColors.purpleDivision},
    {"name": "AquaSplash", "color": GradientColors.aquaSplash},
    {"name": "RedLove", "color": GradientColors.redLove},
    {"name": "CleanMirror", "color": GradientColors.cleanMirror},
    {"name": "PremiumDark", "color": GradientColors.premiumDark},
    {"name": "CochitiLake", "color": GradientColors.cochitiLake},
    {"name": "SummerGames", "color": GradientColors.summerGames},
    {"name": "PassionateRed", "color": GradientColors.passionateRed},
    {"name": "MountainRock", "color": GradientColors.mountainRock},
    {"name": "DesertHump", "color": GradientColors.desertHump},
    {"name": "JungleDay", "color": GradientColors.jungleDay},
    {"name": "PhoenixStart", "color": GradientColors.phoenixStart},
    {"name": "OctoberSilence", "color": GradientColors.octoberSilence},
    {"name": "FarawayRiver", "color": GradientColors.farawayRiver},
    {"name": "AslchemistLab", "color": GradientColors.alchemistLab},
    {"name": "OverSun", "color": GradientColors.overSun},
    {"name": "MarsParty", "color": GradientColors.marsParty},
    {"name": "EternalConstance", "color": GradientColors.eternalConstance},
    {"name": "SummerGames", "color": GradientColors.japanBlush},
    {"name": "JapanBlush", "color": GradientColors.summerGames},
    {"name": "SmilingRain", "color": GradientColors.smilingRain},
    {"name": "Cloudy", "color": GradientColors.cloudy},
    {"name": "BigMango", "color": GradientColors.bigMango},
    {"name": "HealthyWater", "color": GradientColors.healthyWater},
    {"name": "Amour", "color": GradientColors.amour},
    {"name": "StrongStick", "color": GradientColors.strongStick},
    {"name": "BlackGray", "color": GradientColors.blackGray},
    {"name": "PaloAlto", "color": GradientColors.paloAlto},
    {"name": "HappyMemories", "color": GradientColors.happyMemories},
    {"name": "MidnightBloom", "color": GradientColors.midnightBloom},
    {"name": "Crystalline", "color": GradientColors.crystalline},
    {"name": "PartyBliss", "color": GradientColors.partyBliss},
    {"name": "ConfidentCloud", "color": GradientColors.confidentCloud},
    {"name": "LeCocktail", "color": GradientColors.leCocktail},
    {"name": "RiverCity", "color": GradientColors.riverCity},
    {"name": "RozenBerry", "color": GradientColors.rozenBerry},
    {"name": "ChildCare", "color": GradientColors.childCare},
    {"name": "FlyingLemon", "color": GradientColors.flyingLemon},
    {"name": "HiddenJaguar", "color": GradientColors.hiddenJaguar},
    {"name": "Nega", "color": GradientColors.nega},
    {"name": "Seashore", "color": GradientColors.seashore},
    {"name": "MarbleWall", "color": GradientColors.marbleWall},
    {"name": "CheerfulCaramel", "color": GradientColors.cheerfulCaramel},
    {"name": "NightSky", "color": GradientColors.nightSky},
    {"name": "YoungGrass", "color": GradientColors.youngGrass},
    {"name": "ColorfulPeach", "color": GradientColors.colorfulPeach},
    {"name": "GentleCare", "color": GradientColors.gentleCare},
    {"name": "PlumBath", "color": GradientColors.plumBath},
    {"name": "HappyUnicorn", "color": GradientColors.happyUnicorn},
    {"name": "GlassWater", "color": GradientColors.glassWater},
  ];

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("New Colors"),
      ),
      body: ListView(
          children: colorNames.map((colorDetails) {
        return ContainerWidget(
          colorName: "${colorDetails['name']}",
          colors: colorDetails["color"],
        );
      }).toList()),
    );
  }
}
